name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore MySolution.sln

    - name: Build solution
      run: dotnet build MySolution.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test MySolution.sln --no-build --verbosity normal
